---
apiVersion: v1
kind: Service
metadata:
  name: test-action
  namespace: test-action
  labels:
    app: test-action
    service: test-action
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: test-action